name: PR checks

on: pull_request

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn

      - name: lint
        run: yarn lint
      
      - name: Test
        run: yarn test